// Word bank — 4 difficulty tiers, all words must be "soundable" (no purely abstract concepts)
// tier 1: simple, everyday sounds anyone can mimic
// tier 2: more complex or multi-part sounds
// tier 3: challenging combinations or less obvious sounds
// tier 4: hard to perform but still sound-based

export const words = [
  // ── Tier 1 ──────────────────────────────────────────────────────────────
  { id: 1,  tier: 1, text: "Dog" },
  { id: 2,  tier: 1, text: "Cat" },
  { id: 3,  tier: 1, text: "Rain" },
  { id: 4,  tier: 1, text: "Baby crying" },
  { id: 5,  tier: 1, text: "Sneeze" },
  { id: 6,  tier: 1, text: "Car horn" },
  { id: 7,  tier: 1, text: "Doorbell" },
  { id: 8,  tier: 1, text: "Clapping" },
  { id: 9,  tier: 1, text: "Snoring" },
  { id: 10, tier: 1, text: "Laughing" },
  { id: 11, tier: 1, text: "Cow" },
  { id: 12, tier: 1, text: "Frog" },
  { id: 13, tier: 1, text: "Clock ticking" },
  { id: 14, tier: 1, text: "Fire" },
  { id: 15, tier: 1, text: "Wind" },
  { id: 16, tier: 1, text: "Knocking on door" },
  { id: 17, tier: 1, text: "Phone ringing" },
  { id: 18, tier: 1, text: "Bee" },
  { id: 19, tier: 1, text: "Owl" },
  { id: 20, tier: 1, text: "Running water" },
  { id: 21, tier: 1, text: "Heartbeat" },
  { id: 22, tier: 1, text: "Coughing" },
  { id: 23, tier: 1, text: "Hiccup" },
  { id: 24, tier: 1, text: "Burp" },
  { id: 25, tier: 1, text: "Drum" },
  { id: 26, tier: 1, text: "Guitar" },
  { id: 27, tier: 1, text: "Piano" },
  { id: 28, tier: 1, text: "Train" },
  { id: 29, tier: 1, text: "Airplane" },
  { id: 30, tier: 1, text: "Thunder" },
  { id: 31, tier: 1, text: "Footsteps" },
  { id: 32, tier: 1, text: "Balloon popping" },
  { id: 33, tier: 1, text: "Whistle" },
  { id: 34, tier: 1, text: "Alarm clock" },
  { id: 35, tier: 1, text: "Horse" },
  { id: 36, tier: 1, text: "Rooster" },
  { id: 37, tier: 1, text: "Lion" },
  { id: 38, tier: 1, text: "Snake" },
  { id: 39, tier: 1, text: "Pig" },
  { id: 40, tier: 1, text: "Duck" },

  // ── Tier 2 ──────────────────────────────────────────────────────────────
  { id: 41, tier: 2, text: "Thunderstorm" },
  { id: 42, tier: 2, text: "Motorcycle" },
  { id: 43, tier: 2, text: "Crowd cheering" },
  { id: 44, tier: 2, text: "Typewriter" },
  { id: 45, tier: 2, text: "Helicopter" },
  { id: 46, tier: 2, text: "Fireworks" },
  { id: 47, tier: 2, text: "Waterfall" },
  { id: 48, tier: 2, text: "Blender" },
  { id: 49, tier: 2, text: "Toilet flushing" },
  { id: 50, tier: 2, text: "Microwave beeping" },
  { id: 51, tier: 2, text: "Car crash" },
  { id: 52, tier: 2, text: "Glass breaking" },
  { id: 53, tier: 2, text: "Elephant" },
  { id: 54, tier: 2, text: "Whale" },
  { id: 55, tier: 2, text: "Chainsaw" },
  { id: 56, tier: 2, text: "Lawn mower" },
  { id: 57, tier: 2, text: "Ocean waves" },
  { id: 58, tier: 2, text: "Ticking bomb" },
  { id: 59, tier: 2, text: "Power drill" },
  { id: 60, tier: 2, text: "Creaking door" },
  { id: 61, tier: 2, text: "Bowling strike" },
  { id: 62, tier: 2, text: "Basketball dribbling" },
  { id: 63, tier: 2, text: "Record scratch" },
  { id: 64, tier: 2, text: "Ambulance siren" },
  { id: 65, tier: 2, text: "Jackhammer" },
  { id: 66, tier: 2, text: "Church bells" },
  { id: 67, tier: 2, text: "Pop rocks" },
  { id: 68, tier: 2, text: "Bacon frying" },
  { id: 69, tier: 2, text: "Popcorn popping" },
  { id: 70, tier: 2, text: "Ice cracking" },
  { id: 71, tier: 2, text: "Leaves rustling" },
  { id: 72, tier: 2, text: "Squeaky toy" },
  { id: 73, tier: 2, text: "Dial-up modem" },
  { id: 74, tier: 2, text: "Foghorn" },
  { id: 75, tier: 2, text: "Cash register" },
  { id: 76, tier: 2, text: "Slot machine" },
  { id: 77, tier: 2, text: "Dentist drill" },
  { id: 78, tier: 2, text: "Typing on keyboard" },
  { id: 79, tier: 2, text: "Skateboard" },
  { id: 80, tier: 2, text: "Velcro" },

  // ── Tier 3 ──────────────────────────────────────────────────────────────
  { id: 81,  tier: 3, text: "Jungle" },
  { id: 82,  tier: 3, text: "Haunted house" },
  { id: 83,  tier: 3, text: "Rocket launching" },
  { id: 84,  tier: 3, text: "Earthquake" },
  { id: 85,  tier: 3, text: "Submarine" },
  { id: 86,  tier: 3, text: "Monster truck" },
  { id: 87,  tier: 3, text: "Rainstorm on a tent" },
  { id: 88,  tier: 3, text: "Bowling alley" },
  { id: 89,  tier: 3, text: "Stock market floor" },
  { id: 90,  tier: 3, text: "Construction site" },
  { id: 91,  tier: 3, text: "Busy kitchen" },
  { id: 92,  tier: 3, text: "Hospital heart monitor" },
  { id: 93,  tier: 3, text: "Old car engine starting" },
  { id: 94,  tier: 3, text: "Giant clock tower" },
  { id: 95,  tier: 3, text: "Pinball machine" },
  { id: 96,  tier: 3, text: "Swarm of flies" },
  { id: 97,  tier: 3, text: "Ship in a storm" },
  { id: 98,  tier: 3, text: "Avalanche" },
  { id: 99,  tier: 3, text: "Volcano erupting" },
  { id: 100, tier: 3, text: "Dog park" },
  { id: 101, tier: 3, text: "Arcade" },
  { id: 102, tier: 3, text: "Carnival ride" },
  { id: 103, tier: 3, text: "Dentist office" },
  { id: 104, tier: 3, text: "Thunderstorm at sea" },
  { id: 105, tier: 3, text: "Busy highway" },
  { id: 106, tier: 3, text: "Chainsaw juggler" },
  { id: 107, tier: 3, text: "Broken fan" },
  { id: 108, tier: 3, text: "Beehive being disturbed" },
  { id: 109, tier: 3, text: "Rollercoaster drop" },
  { id: 110, tier: 3, text: "Stampede" },
  { id: 111, tier: 3, text: "Squeaky shopping cart" },
  { id: 112, tier: 3, text: "Jackhammer in tunnel" },
  { id: 113, tier: 3, text: "Fax machine" },
  { id: 114, tier: 3, text: "Old pipes in a house" },
  { id: 115, tier: 3, text: "Washing machine spin cycle" },
  { id: 116, tier: 3, text: "Motorbike revving in a garage" },
  { id: 117, tier: 3, text: "Leaves in a tornado" },
  { id: 118, tier: 3, text: "Sneeze in an echo chamber" },
  { id: 119, tier: 3, text: "Deep sea sonar" },
  { id: 120, tier: 3, text: "Cat fight" },

  // ── Tier 4 ──────────────────────────────────────────────────────────────
  { id: 121, tier: 4, text: "Space shuttle reentry" },
  { id: 122, tier: 4, text: "Busy airport terminal" },
  { id: 123, tier: 4, text: "Nuclear reactor hum" },
  { id: 124, tier: 4, text: "Titanic sinking" },
  { id: 125, tier: 4, text: "T-Rex footsteps" },
  { id: 126, tier: 4, text: "Meteor impact" },
  { id: 127, tier: 4, text: "Giant waterfall cavern" },
  { id: 128, tier: 4, text: "Deep inside a tornado" },
  { id: 129, tier: 4, text: "Underwater cave" },
  { id: 130, tier: 4, text: "Server room" },
  { id: 131, tier: 4, text: "Ice age glacier moving" },
  { id: 132, tier: 4, text: "Robot factory" },
  { id: 133, tier: 4, text: "Thunderstorm inside a canyon" },
  { id: 134, tier: 4, text: "Submarine alarm" },
  { id: 135, tier: 4, text: "Rollercoaster in a tunnel" },
  { id: 136, tier: 4, text: "Giant bee swarm attacking" },
  { id: 137, tier: 4, text: "Stampede through a canyon" },
  { id: 138, tier: 4, text: "Freight train braking hard" },
  { id: 139, tier: 4, text: "Crowd panicking" },
  { id: 140, tier: 4, text: "Giant clock tower striking midnight" },
  { id: 141, tier: 4, text: "Lava flowing into ocean" },
  { id: 142, tier: 4, text: "Wrecking ball" },
  { id: 143, tier: 4, text: "Dam breaking" },
  { id: 144, tier: 4, text: "Jet engine warming up" },
  { id: 145, tier: 4, text: "Hailstorm on a metal roof" },
  { id: 146, tier: 4, text: "Whale song underwater" },
  { id: 147, tier: 4, text: "Electrical transformer exploding" },
  { id: 148, tier: 4, text: "Old rollercoaster rickety drop" },
  { id: 149, tier: 4, text: "Bowling alley on fire" },
  { id: 150, tier: 4, text: "Giant snore in a cave" },
  { id: 151, tier: 4, text: "Creaky ship in a storm" },
  { id: 152, tier: 4, text: "Alien spacecraft landing" },
  { id: 153, tier: 4, text: "Crowd doing the wave" },
  { id: 154, tier: 4, text: "Swamp at night" },
  { id: 155, tier: 4, text: "Power plant turbine" },
  { id: 156, tier: 4, text: "Foghorn in dense fog" },
  { id: 157, tier: 4, text: "Jungle at midnight" },
  { id: 158, tier: 4, text: "Earthquake followed by avalanche" },
  { id: 159, tier: 4, text: "Giant xylophone" },
  { id: 160, tier: 4, text: "Rocket engine test fire" },
];
